[package]
name = "rust-game-of-life"
version = "0.1.0"
authors = ["Jiri Hartikka <jiri.hartikka@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
rand = "0.7.3"
gl = "0.10.0"
glfw = "0.23.0"
cgmath = "0.16.1"